//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package org.w3._2005.atom;

import com.google.schemas.contact._2008.Birthday;
import com.google.schemas.contact._2008.CalendarLink;
import com.google.schemas.contact._2008.Event;
import com.google.schemas.contact._2008.ExternalId;
import com.google.schemas.contact._2008.Gender;
import com.google.schemas.contact._2008.GroupMembershipInfo;
import com.google.schemas.contact._2008.Jot;
import com.google.schemas.contact._2008.Language;
import com.google.schemas.contact._2008.Priority;
import com.google.schemas.contact._2008.Relation;
import com.google.schemas.contact._2008.Sensitivity;
import com.google.schemas.contact._2008.UserDefinedField;
import com.google.schemas.contact._2008.Website;
import com.google.schemas.g._2005.Deleted;
import com.google.schemas.g._2005.Email;
import com.google.schemas.g._2005.ExtendedProperty;
import com.google.schemas.g._2005.Im;
import com.google.schemas.g._2005.Name;
import com.google.schemas.g._2005.Organization;
import com.google.schemas.g._2005.PhoneNumber;
import com.google.schemas.g._2005.PostalAddress;
import com.google.schemas.g._2005.StructuredPostalAddress;
import com.google.schemas.g._2005.Where;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;
import org.simpleframework.xml.Root;

import java.util.List;

@Root
public class Feed {

    @Attribute(name = "etag", required = false)
    String etag;
    @Element(name = "title", required = false)
    Title title;
    @Element(name = "generator", required = false)
    Generator generator;
    @Element(name = "author", required = false)
    Author author;
    @Element(name = "startIndex", required = false)
    int startIndex;
    @Element(name = "id", required = false)
    String id;
    @ElementList(entry = "entry", inline = true, required = false)
    List<Entry> entry;
    @Element(name = "totalResults", required = false)
    int totalResults;
    @Element(name = "category", required = false)
    Category category;
    @ElementList(entry = "link", inline = true, required = false)
    List<Link> link;
    @Element(name = "updated", required = false)
    String updated;
    @Element(name = "itemsPerPage", required = false)
    int itemsPerPage;

    public String getEtag() {
        return etag;
    }

    public void setEtag(String value) {
        this.etag = value;
    }

    @Override
    public String toString() {
        return "Feed{" +
                "etag='" + etag + '\'' +
                ", title=" + title +
                ", generator=" + generator +
                ", author=" + author +
                ", startIndex=" + startIndex +
                ", id='" + id + '\'' +
                ", entry=" + entry +
                ", totalResults=" + totalResults +
                ", category=" + category +
                ", link=" + link +
                ", updated='" + updated + '\'' +
                ", itemsPerPage=" + itemsPerPage +
                '}';
    }

    public Title getTitle() {
        return title;
    }

    public void setTitle(Title title) {
        this.title = title;
    }

    public Generator getGenerator() {
        return generator;
    }

    public void setGenerator(Generator generator) {
        this.generator = generator;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public int getStartIndex() {
        return startIndex;
    }

    public void setStartIndex(int startIndex) {
        this.startIndex = startIndex;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public List getEntry() {
        return entry;
    }

    /*public void setEntry(Entry entry) {
        this.entry = entry;
    }*/

    public int getTotalResults() {
        return totalResults;
    }

    public void setTotalResults(int totalResults) {
        this.totalResults = totalResults;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public List getLink() {
        return link;
    }

    public String getUpdated() {
        return updated;
    }

    public void setUpdated(String updated) {
        this.updated = updated;
    }

    public int getItemsPerPage() {
        return itemsPerPage;
    }

    public void setItemsPerPage(int itemsPerPage) {
        this.itemsPerPage = itemsPerPage;
    }

    public static class Category {

        @Attribute(name = "scheme")
        String scheme;

        @Attribute(name = "term")
        String term;

        public String getScheme() {
            return scheme;
        }

        public void setScheme(String value) {
            this.scheme = value;
        }

        public String getTerm() {
            return term;
        }

        public void setTerm(String value) {
            this.term = value;
        }

        @Override
        public String toString() {
            return "Category{" +
                    "scheme='" + scheme + '\'' +
                    ", term='" + term + '\'' +
                    '}';
        }
    }

    public static class Entry {

        @Attribute(name = "etag", required = false)
        String etag;
        @Element(name = "content", required = false)
        Content content;
        @Element(name = "groupMembershipInfo", required = false)
        GroupMembershipInfo groupMembershipInfo;
        @Element(name = "im", required = false)
        Im im;
        @Element(name = "billingInformation", required = false)
        String billingInformation;
        @Element(name = "organization", required = false)
        Organization organization;
        @Element(name = "id", required = false)
        String id;
        @Element(name = "initials", required = false)
        String initials;
        @Element(name = "edited", required = false)
        String edited;
        @Element(name = "nickname", required = false)
        String nickname;
        @Element(name = "externalId", required = false)
        ExternalId externalId;
        @Element(name = "userDefinedField", required = false)
        UserDefinedField userDefinedField;
        @Element(name = "event", required = false)
        Event event;
        @Element(name = "category", required = false)
        Category category;
        @Element(name = "email", required = false)
        Email email;
        @Element(name = "extendedProperty", required = false)
        ExtendedProperty extendedProperty;
        @Element(name = "postalAddress", required = false)
        PostalAddress postalAddress;
        @Element(name = "phoneNumber", required = false)
        PhoneNumber phoneNumber;
        @Element(name = "language", required = false)
        Language language;
        @Element(name = "hobby", required = false)
        String hobby;
        @Element(name = "calendarLink", required = false)
        CalendarLink calendarLink;
        @Element(name = "website", required = false)
        Website website;
        @Element(name = "deleted", required = false)
        Deleted deleted;
        @Element(name = "sensitivity", required = false)
        Sensitivity sensitivity;
        @Element(name = "where", required = false)
        Where where;
        @Element(name = "relation", required = false)
        Relation relation;
        @Element(name = "maidenName", required = false)
        String maidenName;
        @Element(name = "subject", required = false)
        String subject;
        @Element(name = "gender", required = false)
        Gender gender;
        @Element(name = "shortName", required = false)
        String shortName;
        @Element(name = "title", required = false)
        Title title;
        @Element(name = "priority", required = false)
        Priority priority;
        @ElementList(entry = "link", inline = true, required = false)
        List<Link> link;
        @Element(name = "directoryServer", required = false)
        String directoryServer;
        @Element(name = "jot", required = false)
        Jot jot;
        @Element(name = "occupation", required = false)
        String occupation;
        @Element(name = "birthday", required = false)
        Birthday birthday;
        @Element(name = "mileage", required = false)
        String mileage;
        @Element(name = "updated", required = false)
        String updated;
        @Element(name = "name", required = false)
        Name name;
        @Element(name = "structuredPostalAddress", required = false)
        StructuredPostalAddress structuredPostalAddress;

        @Override
        public String toString() {
            return "Entry{" +
                    "etag='" + etag + '\'' +
                    ", content=" + content +
                    ", groupMembershipInfo=" + groupMembershipInfo +
                    ", im=" + im +
                    ", billingInformation='" + billingInformation + '\'' +
                    ", organization=" + organization +
                    ", id='" + id + '\'' +
                    ", initials='" + initials + '\'' +
                    ", edited='" + edited + '\'' +
                    ", nickname='" + nickname + '\'' +
                    ", externalId=" + externalId +
                    ", userDefinedField=" + userDefinedField +
                    ", event=" + event +
                    ", category=" + category +
                    ", email=" + email +
                    ", extendedProperty=" + extendedProperty +
                    ", postalAddress=" + postalAddress +
                    ", phoneNumber=" + phoneNumber +
                    ", language=" + language +
                    ", hobby='" + hobby + '\'' +
                    ", calendarLink=" + calendarLink +
                    ", website=" + website +
                    ", deleted=" + deleted +
                    ", sensitivity=" + sensitivity +
                    ", where=" + where +
                    ", relation=" + relation +
                    ", maidenName='" + maidenName + '\'' +
                    ", subject='" + subject + '\'' +
                    ", gender=" + gender +
                    ", shortName='" + shortName + '\'' +
                    ", title=" + title +
                    ", priority=" + priority +
                    ", link=" + link +
                    ", directoryServer='" + directoryServer + '\'' +
                    ", jot=" + jot +
                    ", occupation='" + occupation + '\'' +
                    ", birthday=" + birthday +
                    ", mileage='" + mileage + '\'' +
                    ", updated='" + updated + '\'' +
                    ", name=" + name +
                    ", structuredPostalAddress=" + structuredPostalAddress +
                    '}';
        }

        public Content getContent() {
            return content;
        }

        public void setContent(Content content) {
            this.content = content;
        }

        public GroupMembershipInfo getGroupMembershipInfo() {
            return groupMembershipInfo;
        }

        public void setGroupMembershipInfo(GroupMembershipInfo groupMembershipInfo) {
            this.groupMembershipInfo = groupMembershipInfo;
        }

        public Im getIm() {
            return im;
        }

        public void setIm(Im im) {
            this.im = im;
        }

        public String getBillingInformation() {
            return billingInformation;
        }

        public void setBillingInformation(String billingInformation) {
            this.billingInformation = billingInformation;
        }

        public Organization getOrganization() {
            return organization;
        }

        public void setOrganization(Organization organization) {
            this.organization = organization;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getInitials() {
            return initials;
        }

        public void setInitials(String initials) {
            this.initials = initials;
        }

        public String getEdited() {
            return edited;
        }

        public void setEdited(String edited) {
            this.edited = edited;
        }

        public String getNickname() {
            return nickname;
        }

        public void setNickname(String nickname) {
            this.nickname = nickname;
        }

        public ExternalId getExternalId() {
            return externalId;
        }

        public void setExternalId(ExternalId externalId) {
            this.externalId = externalId;
        }

        public UserDefinedField getUserDefinedField() {
            return userDefinedField;
        }

        public void setUserDefinedField(UserDefinedField userDefinedField) {
            this.userDefinedField = userDefinedField;
        }

        public Event getEvent() {
            return event;
        }

        public void setEvent(Event event) {
            this.event = event;
        }

        public Category getCategory() {
            return category;
        }

        public void setCategory(Category category) {
            this.category = category;
        }

        public Email getEmail() {
            return email;
        }

        public void setEmail(Email email) {
            this.email = email;
        }

        public ExtendedProperty getExtendedProperty() {
            return extendedProperty;
        }

        public void setExtendedProperty(ExtendedProperty extendedProperty) {
            this.extendedProperty = extendedProperty;
        }

        public PostalAddress getPostalAddress() {
            return postalAddress;
        }

        public void setPostalAddress(PostalAddress postalAddress) {
            this.postalAddress = postalAddress;
        }

        public PhoneNumber getPhoneNumber() {
            return phoneNumber;
        }

        public void setPhoneNumber(PhoneNumber phoneNumber) {
            this.phoneNumber = phoneNumber;
        }

        public Language getLanguage() {
            return language;
        }

        public void setLanguage(Language language) {
            this.language = language;
        }

        public String getHobby() {
            return hobby;
        }

        public void setHobby(String hobby) {
            this.hobby = hobby;
        }

        public CalendarLink getCalendarLink() {
            return calendarLink;
        }

        public void setCalendarLink(CalendarLink calendarLink) {
            this.calendarLink = calendarLink;
        }

        public Website getWebsite() {
            return website;
        }

        public void setWebsite(Website website) {
            this.website = website;
        }

        public Deleted getDeleted() {
            return deleted;
        }

        public void setDeleted(Deleted deleted) {
            this.deleted = deleted;
        }

        public Sensitivity getSensitivity() {
            return sensitivity;
        }

        public void setSensitivity(Sensitivity sensitivity) {
            this.sensitivity = sensitivity;
        }

        public Where getWhere() {
            return where;
        }

        public void setWhere(Where where) {
            this.where = where;
        }

        public Relation getRelation() {
            return relation;
        }

        public void setRelation(Relation relation) {
            this.relation = relation;
        }

        public String getMaidenName() {
            return maidenName;
        }

        public void setMaidenName(String maidenName) {
            this.maidenName = maidenName;
        }

        public String getSubject() {
            return subject;
        }

        public void setSubject(String subject) {
            this.subject = subject;
        }

        public Gender getGender() {
            return gender;
        }

        public void setGender(Gender gender) {
            this.gender = gender;
        }

        public String getShortName() {
            return shortName;
        }

        public void setShortName(String shortName) {
            this.shortName = shortName;
        }

        public Title getTitle() {
            return title;
        }

        public void setTitle(Title title) {
            this.title = title;
        }

        public Priority getPriority() {
            return priority;
        }

        public void setPriority(Priority priority) {
            this.priority = priority;
        }

        public List getLink() {
            return link;
        }

        /* public void setLink(List<Link> link) {
            this.link = link;
        } */

        public String getDirectoryServer() {
            return directoryServer;
        }

        public void setDirectoryServer(String directoryServer) {
            this.directoryServer = directoryServer;
        }

        public Jot getJot() {
            return jot;
        }

        public void setJot(Jot jot) {
            this.jot = jot;
        }

        public String getOccupation() {
            return occupation;
        }

        public void setOccupation(String occupation) {
            this.occupation = occupation;
        }

        public Birthday getBirthday() {
            return birthday;
        }

        public void setBirthday(Birthday birthday) {
            this.birthday = birthday;
        }

        public String getMileage() {
            return mileage;
        }

        public void setMileage(String mileage) {
            this.mileage = mileage;
        }

        public String getUpdated() {
            return updated;
        }

        public void setUpdated(String updated) {
            this.updated = updated;
        }

        public Name getName() {
            return name;
        }

        public void setName(Name name) {
            this.name = name;
        }

        public StructuredPostalAddress getStructuredPostalAddress() {
            return structuredPostalAddress;
        }

        public void setStructuredPostalAddress(StructuredPostalAddress structuredPostalAddress) {
            this.structuredPostalAddress = structuredPostalAddress;
        }

        public String getEtag() {
            return etag;
        }

        public void setEtag(String value) {
            this.etag = value;
        }

    }

    public static class Link {

        @Attribute(name = "href")
        protected String href;
        @Attribute(name = "length", required = false)
        protected Long length;
        @Attribute(name = "rel", required = false)
        protected String rel;
        @Attribute(name = "title", required = false)
        protected String title;
        @Attribute(name = "type")
        protected String type;
        @Attribute(name = "etag", required = false)
        String etag;

        public String getEtag() {
            return etag;
        }

        public void setEtag(String etag) {
            this.etag = etag;
        }

        @Override
        public String toString() {
            return "Link{" +
                    "href='" + href + '\'' +
                    ", length=" + length +
                    ", rel='" + rel + '\'' +
                    ", title='" + title + '\'' +
                    ", type='" + type + '\'' +
                    '}';
        }

        public String getHref() {
            return href;
        }

        public void setHref(String value) {
            this.href = value;
        }

        public Long getLength() {
            return length;
        }

        public void setLength(Long value) {
            this.length = value;
        }

        public String getRel() {
            return rel;
        }

        public void setRel(String value) {
            this.rel = value;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String value) {
            this.title = value;
        }

        public String getType() {
            return type;
        }

        public void setType(String value) {
            this.type = value;
        }

    }

}
