//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package org.w3._2005.atom;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2005.atom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Email_QNAME = new QName("http://www.w3.org/2005/Atom", "email");
    private final static QName _Id_QNAME = new QName("http://www.w3.org/2005/Atom", "id");
    private final static QName _Uri_QNAME = new QName("http://www.w3.org/2005/Atom", "uri");
    private final static QName _Published_QNAME = new QName("http://www.w3.org/2005/Atom", "published");
    private final static QName _Updated_QNAME = new QName("http://www.w3.org/2005/Atom", "updated");
    private final static QName _Name_QNAME = new QName("http://www.w3.org/2005/Atom", "name");
    private final static QName _FeedEntryCategory_QNAME = new QName("http://www.w3.org/2005/Atom", "category");
    private final static QName _FeedEntryLink_QNAME = new QName("http://www.w3.org/2005/Atom", "link");
    private final static QName _FeedEntry_QNAME = new QName("http://www.w3.org/2005/Atom", "entry");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2005.atom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Summary }
     * 
     */
    public Summary createSummary() {
        return new Summary();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Generator }
     * 
     */
    public Generator createGenerator() {
        return new Generator();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Feed.Entry }
     * 
     */
    public Feed.Entry createFeedEntry() {
        return new Feed.Entry();
    }

    /**
     * Create an instance of {@link Feed.Category }
     * 
     */
    public Feed.Category createFeedCategory() {
        return new Feed.Category();
    }

    /**
     * Create an instance of {@link Feed.Link }
     * 
     */
    public Feed.Link createFeedLink() {
        return new Feed.Link();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link Rights }
     * 
     */
    public Rights createRights() {
        return new Rights();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<String>(_Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "published")
    public JAXBElement<String> createPublished(String value) {
        return new JAXBElement<String>(_Published_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "updated")
    public JAXBElement<String> createUpdated(String value) {
        return new JAXBElement<String>(_Updated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feed.Category }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "category", scope = Feed.Entry.class)
    public JAXBElement<Feed.Category> createFeedEntryCategory(Feed.Category value) {
        return new JAXBElement<Feed.Category>(_FeedEntryCategory_QNAME, Feed.Category.class, Feed.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feed.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "link", scope = Feed.Entry.class)
    public JAXBElement<Feed.Link> createFeedEntryLink(Feed.Link value) {
        return new JAXBElement<Feed.Link>(_FeedEntryLink_QNAME, Feed.Link.class, Feed.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feed.Entry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "entry", scope = Feed.class)
    public JAXBElement<Feed.Entry> createFeedEntry(Feed.Entry value) {
        return new JAXBElement<Feed.Entry>(_FeedEntry_QNAME, Feed.Entry.class, Feed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feed.Category }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "category", scope = Feed.class)
    public JAXBElement<Feed.Category> createFeedCategory(Feed.Category value) {
        return new JAXBElement<Feed.Category>(_FeedEntryCategory_QNAME, Feed.Category.class, Feed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feed.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "link", scope = Feed.class)
    public JAXBElement<Feed.Link> createFeedLink(Feed.Link value) {
        return new JAXBElement<Feed.Link>(_FeedEntryLink_QNAME, Feed.Link.class, Feed.class, value);
    }

}
