//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2005.atom.Author;
import org.w3._2005.atom.Content;
import org.w3._2005.atom.Contributor;
import org.w3._2005.atom.Rights;
import org.w3._2005.atom.Summary;
import org.w3._2005.atom.Title;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://schemas.google.com/g/2005}gdata_entry" minOccurs="0"/>
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="readOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entry"
})
@XmlRootElement(name = "entryLink")
public class EntryLink {

    @XmlElement(namespace = "http://www.w3.org/2005/Atom")
    protected EntryLink.Entry entry;
    @XmlAttribute(name = "href")
    protected String href;
    @XmlAttribute(name = "readOnly")
    protected Boolean readOnly;
    @XmlAttribute(name = "rel")
    protected String rel;

    /**
     * Gets the value of the entry property.
     * 
     * @return
     *     possible object is
     *     {@link EntryLink.Entry }
     *     
     */
    public EntryLink.Entry getEntry() {
        return entry;
    }

    /**
     * Sets the value of the entry property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryLink.Entry }
     *     
     */
    public void setEntry(EntryLink.Entry value) {
        this.entry = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the readOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadOnly() {
        return readOnly;
    }

    /**
     * Sets the value of the readOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadOnly(Boolean value) {
        this.readOnly = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel(String value) {
        this.rel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.w3.org/2007/app}control"/>
     *         &lt;element ref="{http://www.w3.org/2007/app}edited"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}author"/>
     *         &lt;group ref="{http://schemas.google.com/g/2005}atom_category"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}content"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}contributor"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}id"/>
     *         &lt;group ref="{http://schemas.google.com/g/2005}atom_link"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}published"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}updated"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}rights"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}summary"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}title"/>
     *       &lt;/choice>
     *       &lt;attribute ref="{http://schemas.google.com/g/2005}etag"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "controlOrEditedOrAuthor"
    })
    public static class Entry {

        @XmlElementRefs({
            @XmlElementRef(name = "content", namespace = "http://www.w3.org/2005/Atom", type = Content.class, required = false),
            @XmlElementRef(name = "author", namespace = "http://www.w3.org/2005/Atom", type = Author.class, required = false),
            @XmlElementRef(name = "id", namespace = "http://www.w3.org/2005/Atom", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "control", namespace = "http://www.w3.org/2007/app", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "edited", namespace = "http://www.w3.org/2007/app", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "link", namespace = "http://www.w3.org/2005/Atom", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "category", namespace = "http://www.w3.org/2005/Atom", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "contributor", namespace = "http://www.w3.org/2005/Atom", type = Contributor.class, required = false),
            @XmlElementRef(name = "title", namespace = "http://www.w3.org/2005/Atom", type = Title.class, required = false),
            @XmlElementRef(name = "summary", namespace = "http://www.w3.org/2005/Atom", type = Summary.class, required = false),
            @XmlElementRef(name = "published", namespace = "http://www.w3.org/2005/Atom", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "updated", namespace = "http://www.w3.org/2005/Atom", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "rights", namespace = "http://www.w3.org/2005/Atom", type = Rights.class, required = false)
        })
        protected List<Object> controlOrEditedOrAuthor;
        @XmlAttribute(name = "etag", namespace = "http://schemas.google.com/g/2005")
        protected String etag;

        /**
         * Gets the value of the controlOrEditedOrAuthor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the controlOrEditedOrAuthor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getControlOrEditedOrAuthor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Content }
         * {@link Author }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link AppDraft }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link EntryLink.Entry.Link }{@code >}
         * {@link JAXBElement }{@code <}{@link EntryLink.Entry.Category }{@code >}
         * {@link Contributor }
         * {@link Title }
         * {@link Summary }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link Rights }
         * 
         * 
         */
        public List<Object> getControlOrEditedOrAuthor() {
            if (controlOrEditedOrAuthor == null) {
                controlOrEditedOrAuthor = new ArrayList<Object>();
            }
            return this.controlOrEditedOrAuthor;
        }

        /**
         * Gets the value of the etag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEtag() {
            return etag;
        }

        /**
         * Sets the value of the etag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEtag(String value) {
            this.etag = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="scheme" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="term" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Category {

            @XmlAttribute(name = "label")
            protected String label;
            @XmlAttribute(name = "scheme")
            protected String scheme;
            @XmlAttribute(name = "term", required = true)
            protected String term;
            @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
            protected String lang;

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the scheme property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScheme() {
                return scheme;
            }

            /**
             * Sets the value of the scheme property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScheme(String value) {
                this.scheme = value;
            }

            /**
             * Gets the value of the term property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTerm() {
                return term;
            }

            /**
             * Sets the value of the term property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTerm(String value) {
                this.term = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="hreflang" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Link {

            @XmlAttribute(name = "href", required = true)
            protected String href;
            @XmlAttribute(name = "hreflang")
            protected String hreflang;
            @XmlAttribute(name = "length")
            protected Long length;
            @XmlAttribute(name = "rel")
            protected String rel;
            @XmlAttribute(name = "title")
            protected String title;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
            protected String lang;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

            /**
             * Gets the value of the hreflang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHreflang() {
                return hreflang;
            }

            /**
             * Sets the value of the hreflang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHreflang(String value) {
                this.hreflang = value;
            }

            /**
             * Gets the value of the length property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setLength(Long value) {
                this.length = value;
            }

            /**
             * Gets the value of the rel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRel() {
                return rel;
            }

            /**
             * Sets the value of the rel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRel(String value) {
                this.rel = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }

        }

    }

}
