//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;
import org.w3._2005.atom.Author;
import org.w3._2005.atom.Content;
import org.w3._2005.atom.Contributor;
import org.w3._2005.atom.Rights;
import org.w3._2005.atom.Summary;
import org.w3._2005.atom.Title;

import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://schemas.google.com/g/2005}gdata_entry" minOccurs="0"/>
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="readOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

@Root
public class EntryLink {

    @Element(required = false)
    protected List<EntryLink.Entry> entry;
    @Attribute(name = "href", required = false)
    protected String href;
    @Attribute(name = "readOnly", required = false)
    protected boolean readOnly;
    @Attribute(name = "rel", required = false)
    protected String rel;

    public List<EntryLink.Entry> getEntry() {
        return entry;
    }

    public void setEntry(List<EntryLink.Entry> value) {
        this.entry = value;
    }

    public String getHref() {
        return href;
    }

    public void setHref(String value) {
        this.href = value;
    }

    public boolean isReadOnly() {
        return readOnly;
    }

    public void setReadOnly(boolean value) {
        this.readOnly = value;
    }

    public String getRel() {
        return rel;
    }

    public void setRel(String value) {
        this.rel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.w3.org/2007/app}control"/>
     *         &lt;element ref="{http://www.w3.org/2007/app}edited"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}author"/>
     *         &lt;group ref="{http://schemas.google.com/g/2005}atom_category"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}content"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}contributor"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}id"/>
     *         &lt;group ref="{http://schemas.google.com/g/2005}atom_link"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}published"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}updated"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}rights"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}summary"/>
     *         &lt;element ref="{http://www.w3.org/2005/Atom}title"/>
     *       &lt;/choice>
     *       &lt;attribute ref="{http://schemas.google.com/g/2005}etag"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Entry {
        @Attribute(name = "etag", required = false)
        protected String etag;
        @Element(name = "content", required = false)
        Content content;
        @Element(name = "author", required = false)
        Author author;
        @Element(name = "id", required = false)
        String id;
        @Element(name = "control", required = false)
        AppDraft control;
        @Element(name = "edited", required = false)
        String edited;
        @Element(name = "link", required = false)
        Link link;
        @Element(name = "category", required = false)
        Category category;
        @Element(name = "contributor", required = false)
        Contributor contributor;
        @Element(name = "title", required = false)
        Title title;
        @Element(name = "summary", required = false)
        Summary summary;
        @Element(name = "published", required = false)
        String published;
        @Element(name = "updated", required = false)
        String updated;
        @Element(name = "rights", required = false)
        Rights rights;

        public Content getContent() {
            return content;
        }

        public void setContent(Content content) {
            this.content = content;
        }

        public Author getAuthor() {
            return author;
        }

        public void setAuthor(Author author) {
            this.author = author;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public AppDraft getControl() {
            return control;
        }

        public void setControl(AppDraft control) {
            this.control = control;
        }

        public String getEdited() {
            return edited;
        }

        public void setEdited(String edited) {
            this.edited = edited;
        }

        public Link getLink() {
            return link;
        }

        public void setLink(Link link) {
            this.link = link;
        }

        public Category getCategory() {
            return category;
        }

        public void setCategory(Category category) {
            this.category = category;
        }

        public Contributor getContributor() {
            return contributor;
        }

        public void setContributor(Contributor contributor) {
            this.contributor = contributor;
        }

        public Title getTitle() {
            return title;
        }

        public void setTitle(Title title) {
            this.title = title;
        }

        public Summary getSummary() {
            return summary;
        }

        public void setSummary(Summary summary) {
            this.summary = summary;
        }

        public String getPublished() {
            return published;
        }

        public void setPublished(String published) {
            this.published = published;
        }

        public String getUpdated() {
            return updated;
        }

        public void setUpdated(String updated) {
            this.updated = updated;
        }

        public Rights getRights() {
            return rights;
        }

        public void setRights(Rights rights) {
            this.rights = rights;
        }

        /**
         * Gets the value of the etag property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getEtag() {
            return etag;
        }

        /**
         * Sets the value of the etag property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setEtag(String value) {
            this.etag = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="scheme" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="term" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        public static class Category {

            @Attribute(name = "label", required = false)
            protected String label;
            @Attribute(name = "scheme", required = false)
            protected String scheme;
            @Attribute(name = "term")
            protected String term;
            @Attribute(name = "lang", required = false)
            protected String lang;

            public String getLabel() {
                return label;
            }

            public void setLabel(String value) {
                this.label = value;
            }

            public String getScheme() {
                return scheme;
            }

            public void setScheme(String value) {
                this.scheme = value;
            }

            public String getTerm() {
                return term;
            }

            public void setTerm(String value) {
                this.term = value;
            }

            public String getLang() {
                return lang;
            }

            public void setLang(String value) {
                this.lang = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="hreflang" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        public static class Link {

            @Attribute(name = "href")
            protected String href;
            @Attribute(name = "hreflang", required = false)
            protected String hreflang;
            @Attribute(name = "length", required = false)
            protected Long length;
            @Attribute(name = "rel", required = false)
            protected String rel;
            @Attribute(name = "title", required = false)
            protected String title;
            @Attribute(name = "type", required = false)
            protected String type;
            @Attribute(name = "lang", required = false)
            protected String lang;

            public String getHref() {
                return href;
            }

            public void setHref(String value) {
                this.href = value;
            }

            public String getHreflang() {
                return hreflang;
            }

            public void setHreflang(String value) {
                this.hreflang = value;
            }

            public Long getLength() {
                return length;
            }

            public void setLength(Long value) {
                this.length = value;
            }

            public String getRel() {
                return rel;
            }

            public void setRel(String value) {
                this.rel = value;
            }

            public String getTitle() {
                return title;
            }

            public void setTitle(String value) {
                this.title = value;
            }

            public String getType() {
                return type;
            }

            public void setType(String value) {
                this.type = value;
            }

            public String getLang() {
                return lang;
            }

            public void setLang(String value) {
                this.lang = value;
            }

        }

    }

}
