//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.google.com/g/2005}additionalName"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}familyName"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}fullName"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}givenName"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}namePrefix"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}nameSuffix"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */

public class Name {
    @Element(name = "additionalName", required = false)
    AdditionalName additionalName;
    @Element(name = "fullName", required = false)
    FullName fullName;
    @Element(name = "namePrefix", required = false)
    FullName namePrefix;
    @Element(name = "familyName", required = false)
    FamilyName familyName;
    @Element(name = "givenName", required = false)
    GivenName givenName;
    @Element(name = "nameSuffix", required = false)
    String nameSuffix;

    public AdditionalName getAdditionalName() {
        return additionalName;
    }

    public void setAdditionalName(AdditionalName additionalName) {
        this.additionalName = additionalName;
    }

    public FullName getFullName() {
        return fullName;
    }

    public void setFullName(FullName fullName) {
        this.fullName = fullName;
    }

    public FullName getNamePrefix() {
        return namePrefix;
    }

    public void setNamePrefix(FullName namePrefix) {
        this.namePrefix = namePrefix;
    }

    public FamilyName getFamilyName() {
        return familyName;
    }

    public void setFamilyName(FamilyName familyName) {
        this.familyName = familyName;
    }

    public GivenName getGivenName() {
        return givenName;
    }

    public void setGivenName(GivenName givenName) {
        this.givenName = givenName;
    }

    public String getNameSuffix() {
        return nameSuffix;
    }

    public void setNameSuffix(String nameSuffix) {
        this.nameSuffix = nameSuffix;
    }
}
