//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.google.schemas.g._2005 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Postcode_QNAME = new QName("http://schemas.google.com/g/2005", "postcode");
    private final static QName _OrgTitle_QNAME = new QName("http://schemas.google.com/g/2005", "orgTitle");
    private final static QName _Subregion_QNAME = new QName("http://schemas.google.com/g/2005", "subregion");
    private final static QName _Neighborhood_QNAME = new QName("http://schemas.google.com/g/2005", "neighborhood");
    private final static QName _Region_QNAME = new QName("http://schemas.google.com/g/2005", "region");
    private final static QName _Pobox_QNAME = new QName("http://schemas.google.com/g/2005", "pobox");
    private final static QName _OrgJobDescription_QNAME = new QName("http://schemas.google.com/g/2005", "orgJobDescription");
    private final static QName _NameSuffix_QNAME = new QName("http://schemas.google.com/g/2005", "nameSuffix");
    private final static QName _OrgSymbol_QNAME = new QName("http://schemas.google.com/g/2005", "orgSymbol");
    private final static QName _Agent_QNAME = new QName("http://schemas.google.com/g/2005", "agent");
    private final static QName _Housename_QNAME = new QName("http://schemas.google.com/g/2005", "housename");
    private final static QName _City_QNAME = new QName("http://schemas.google.com/g/2005", "city");
    private final static QName _OrgDepartment_QNAME = new QName("http://schemas.google.com/g/2005", "orgDepartment");
    private final static QName _FormattedAddress_QNAME = new QName("http://schemas.google.com/g/2005", "formattedAddress");
    private final static QName _NamePrefix_QNAME = new QName("http://schemas.google.com/g/2005", "namePrefix");
    private final static QName _Street_QNAME = new QName("http://schemas.google.com/g/2005", "street");
    private final static QName _EntryLinkEntryCategory_QNAME = new QName("http://www.w3.org/2005/Atom", "category");
    private final static QName _EntryLinkEntryLink_QNAME = new QName("http://www.w3.org/2005/Atom", "link");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.google.schemas.g._2005
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntryLink }
     * 
     */
    public EntryLink createEntryLink() {
        return new EntryLink();
    }

    /**
     * Create an instance of {@link EntryLink.Entry }
     * 
     */
    public EntryLink.Entry createEntryLinkEntry() {
        return new EntryLink.Entry();
    }

    /**
     * Create an instance of {@link GdataWhen }
     * 
     */
    public GdataWhen createGdataWhen() {
        return new GdataWhen();
    }

    /**
     * Create an instance of {@link When }
     * 
     */
    public When createWhen() {
        return new When();
    }

    /**
     * Create an instance of {@link Reminder }
     * 
     */
    public Reminder createReminder() {
        return new Reminder();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link FamilyName }
     * 
     */
    public FamilyName createFamilyName() {
        return new FamilyName();
    }

    /**
     * Create an instance of {@link Where }
     * 
     */
    public Where createWhere() {
        return new Where();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link OrgName }
     * 
     */
    public OrgName createOrgName() {
        return new OrgName();
    }

    /**
     * Create an instance of {@link Im }
     * 
     */
    public Im createIm() {
        return new Im();
    }

    /**
     * Create an instance of {@link GivenName }
     * 
     */
    public GivenName createGivenName() {
        return new GivenName();
    }

    /**
     * Create an instance of {@link FullName }
     * 
     */
    public FullName createFullName() {
        return new FullName();
    }

    /**
     * Create an instance of {@link StructuredPostalAddress }
     * 
     */
    public StructuredPostalAddress createStructuredPostalAddress() {
        return new StructuredPostalAddress();
    }

    /**
     * Create an instance of {@link ExtendedProperty }
     * 
     */
    public ExtendedProperty createExtendedProperty() {
        return new ExtendedProperty();
    }

    /**
     * Create an instance of {@link Deleted }
     * 
     */
    public Deleted createDeleted() {
        return new Deleted();
    }

    /**
     * Create an instance of {@link PhoneNumber }
     * 
     */
    public PhoneNumber createPhoneNumber() {
        return new PhoneNumber();
    }

    /**
     * Create an instance of {@link PostalAddress }
     * 
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link AdditionalName }
     * 
     */
    public AdditionalName createAdditionalName() {
        return new AdditionalName();
    }

    /**
     * Create an instance of {@link AppDraft }
     * 
     */
    public AppDraft createAppDraft() {
        return new AppDraft();
    }

    /**
     * Create an instance of {@link EntryLink.Entry.Category }
     * 
     */
    public EntryLink.Entry.Category createEntryLinkEntryCategory() {
        return new EntryLink.Entry.Category();
    }

    /**
     * Create an instance of {@link EntryLink.Entry.Link }
     * 
     */
    public EntryLink.Entry.Link createEntryLinkEntryLink() {
        return new EntryLink.Entry.Link();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "postcode")
    public JAXBElement<String> createPostcode(String value) {
        return new JAXBElement<String>(_Postcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "orgTitle")
    public JAXBElement<String> createOrgTitle(String value) {
        return new JAXBElement<String>(_OrgTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "subregion")
    public JAXBElement<String> createSubregion(String value) {
        return new JAXBElement<String>(_Subregion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "neighborhood")
    public JAXBElement<String> createNeighborhood(String value) {
        return new JAXBElement<String>(_Neighborhood_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "pobox")
    public JAXBElement<String> createPobox(String value) {
        return new JAXBElement<String>(_Pobox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "orgJobDescription")
    public JAXBElement<String> createOrgJobDescription(String value) {
        return new JAXBElement<String>(_OrgJobDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "nameSuffix")
    public JAXBElement<String> createNameSuffix(String value) {
        return new JAXBElement<String>(_NameSuffix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "orgSymbol")
    public JAXBElement<String> createOrgSymbol(String value) {
        return new JAXBElement<String>(_OrgSymbol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "agent")
    public JAXBElement<String> createAgent(String value) {
        return new JAXBElement<String>(_Agent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "housename")
    public JAXBElement<String> createHousename(String value) {
        return new JAXBElement<String>(_Housename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "orgDepartment")
    public JAXBElement<String> createOrgDepartment(String value) {
        return new JAXBElement<String>(_OrgDepartment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "formattedAddress")
    public JAXBElement<String> createFormattedAddress(String value) {
        return new JAXBElement<String>(_FormattedAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "namePrefix")
    public JAXBElement<String> createNamePrefix(String value) {
        return new JAXBElement<String>(_NamePrefix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.google.com/g/2005", name = "street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryLink.Entry.Category }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "category", scope = EntryLink.Entry.class)
    public JAXBElement<EntryLink.Entry.Category> createEntryLinkEntryCategory(EntryLink.Entry.Category value) {
        return new JAXBElement<EntryLink.Entry.Category>(_EntryLinkEntryCategory_QNAME, EntryLink.Entry.Category.class, EntryLink.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryLink.Entry.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "link", scope = EntryLink.Entry.class)
    public JAXBElement<EntryLink.Entry.Link> createEntryLinkEntryLink(EntryLink.Entry.Link value) {
        return new JAXBElement<EntryLink.Entry.Link>(_EntryLinkEntryLink_QNAME, EntryLink.Entry.Link.class, EntryLink.Entry.class, value);
    }

}
