//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgDepartment"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgJobDescription"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgName"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgSymbol"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgTitle"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}where"/>
 *       &lt;/choice>
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orgDepartmentOrOrgJobDescriptionOrOrgName"
})
@XmlRootElement(name = "organization")
public class Organization {

    @XmlElementRefs({
        @XmlElementRef(name = "orgTitle", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "where", namespace = "http://schemas.google.com/g/2005", type = Where.class, required = false),
        @XmlElementRef(name = "orgJobDescription", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "orgName", namespace = "http://schemas.google.com/g/2005", type = OrgName.class, required = false),
        @XmlElementRef(name = "orgDepartment", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "orgSymbol", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false)
    })
    protected List<Object> orgDepartmentOrOrgJobDescriptionOrOrgName;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "primary")
    protected Boolean primary;
    @XmlAttribute(name = "rel")
    protected String rel;

    /**
     * Gets the value of the orgDepartmentOrOrgJobDescriptionOrOrgName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orgDepartmentOrOrgJobDescriptionOrOrgName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrgDepartmentOrOrgJobDescriptionOrOrgName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Where }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link OrgName }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getOrgDepartmentOrOrgJobDescriptionOrOrgName() {
        if (orgDepartmentOrOrgJobDescriptionOrOrgName == null) {
            orgDepartmentOrOrgJobDescriptionOrOrgName = new ArrayList<Object>();
        }
        return this.orgDepartmentOrOrgJobDescriptionOrOrgName;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimary(Boolean value) {
        this.primary = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel(String value) {
        this.rel = value;
    }

}
