//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgDepartment"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgJobDescription"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgName"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgSymbol"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}orgTitle"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}where"/>
 *       &lt;/choice>
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public class Organization {

    @Attribute(name = "label", required = false)
    protected String label;
    @Attribute(name = "primary", required = false)
    protected boolean primary;
    @Attribute(name = "rel", required = false)
    protected String rel;
    @Element(name = "orgTitle", required = false)
    String orgTitle;
    @Element(name = "where", required = false)
    String where;
    @Element(name = "orgJobDescription", required = false)
    String orgJobDescription;
    @Element(name = "orgName", required = false)
    String orgName;
    @Element(name = "orgDepartment", required = false)
    String orgDepartment;
    @Element(name = "orgSymbol", required = false)
    String orgSymbol;

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public boolean isPrimary() {
        return primary;
    }

    public void setPrimary(boolean value) {
        this.primary = value;
    }

    public String getRel() {
        return rel;
    }

    public void setRel(String value) {
        this.rel = value;
    }

    public String getOrgTitle() {
        return orgTitle;
    }

    public void setOrgTitle(String orgTitle) {
        this.orgTitle = orgTitle;
    }

    public String getWhere() {
        return where;
    }

    public void setWhere(String where) {
        this.where = where;
    }

    public String getOrgJobDescription() {
        return orgJobDescription;
    }

    public void setOrgJobDescription(String orgJobDescription) {
        this.orgJobDescription = orgJobDescription;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgDepartment() {
        return orgDepartment;
    }

    public void setOrgDepartment(String orgDepartment) {
        this.orgDepartment = orgDepartment;
    }

    public String getOrgSymbol() {
        return orgSymbol;
    }

    public void setOrgSymbol(String orgSymbol) {
        this.orgSymbol = orgSymbol;
    }

}
