//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.google.com/g/2005", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.google.schemas.g._2005;
