//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import org.simpleframework.xml.Attribute;

/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="absoluteTime">
 *         &lt;simpleType>
 *           &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}date {http://www.w3.org/2001/XMLSchema}dateTime">
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hours" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minutes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public class Reminder {

    @Attribute(name = "absoluteTime", required = false)
    protected String absoluteTime;
    @Attribute(name = "days", required = false)
    protected int days;
    @Attribute(name = "hours", required = false)
    protected int hours;
    @Attribute(name = "method", required = false)
    protected String method;
    @Attribute(name = "minutes", required = false)
    protected int minutes;

    public String getAbsoluteTime() {
        return absoluteTime;
    }

    public void setAbsoluteTime(String value) {
        this.absoluteTime = value;
    }

    public int getDays() {
        return days;
    }

    public void setDays(int value) {
        this.days = value;
    }

    public int getHours() {
        return hours;
    }

    public void setHours(int value) {
        this.hours = value;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String value) {
        this.method = value;
    }

    public int getMinutes() {
        return minutes;
    }

    public void setMinutes(int value) {
        this.minutes = value;
    }

}
