//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;

/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.google.com/g/2005}agent"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}city"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}country"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}formattedAddress"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}housename"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}neighborhood"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}pobox"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}postcode"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}region"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}street"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}subregion"/>
 *       &lt;/choice>
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mailClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public class StructuredPostalAddress {

    @Attribute(name = "label", required = false)
    protected String label;
    @Attribute(name = "mailClass", required = false)
    protected String mailClass;
    @Attribute(name = "primary", required = false)
    protected boolean primary;
    @Attribute(name = "rel", required = false)
    protected String rel;
    @Attribute(name = "usage", required = false)
    protected String usage;
    @Element(name = "formattedAddress", required = false)
    String formattedAddress;
    @Element(name = "housename", required = false)
    String housename;
    @Element(name = "postcode", required = false)
    String postcode;
    @Element(name = "pobox", required = false)
    String pobox;
    @Element(name = "neighborhood", required = false)
    String neighborhood;
    @Element(name = "subregion", required = false)
    String subregion;
    @Element(name = "country", required = false)
    Country country;
    @Element(name = "city", required = false)
    String city;
    @Element(name = "agent", required = false)
    String agent;
    @Element(name = "street", required = false)
    String street;
    @Element(name = "region", required = false)
    String region;

    public boolean getPrimary() {
        return primary;
    }

    public String getFormattedAddress() {
        return formattedAddress;
    }

    public void setFormattedAddress(String formattedAddress) {
        this.formattedAddress = formattedAddress;
    }

    public String getHousename() {
        return housename;
    }

    public void setHousename(String housename) {
        this.housename = housename;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getPobox() {
        return pobox;
    }

    public void setPobox(String pobox) {
        this.pobox = pobox;
    }

    public String getNeighborhood() {
        return neighborhood;
    }

    public void setNeighborhood(String neighborhood) {
        this.neighborhood = neighborhood;
    }

    public String getSubregion() {
        return subregion;
    }

    public void setSubregion(String subregion) {
        this.subregion = subregion;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAgent() {
        return agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public String getMailClass() {
        return mailClass;
    }

    public void setMailClass(String value) {
        this.mailClass = value;
    }

    public boolean isPrimary() {
        return primary;
    }

    public void setPrimary(boolean value) {
        this.primary = value;
    }

    public String getRel() {
        return rel;
    }

    public void setRel(String value) {
        this.rel = value;
    }

    public String getUsage() {
        return usage;
    }

    public void setUsage(String value) {
        this.usage = value;
    }

}
