//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.g._2005;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.google.com/g/2005}agent"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}city"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}country"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}formattedAddress"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}housename"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}neighborhood"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}pobox"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}postcode"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}region"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}street"/>
 *         &lt;element ref="{http://schemas.google.com/g/2005}subregion"/>
 *       &lt;/choice>
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mailClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="usage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agentOrCityOrCountry"
})
@XmlRootElement(name = "structuredPostalAddress")
public class StructuredPostalAddress {

    @XmlElementRefs({
        @XmlElementRef(name = "formattedAddress", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "housename", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "postcode", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pobox", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "neighborhood", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subregion", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "country", namespace = "http://schemas.google.com/g/2005", type = Country.class, required = false),
        @XmlElementRef(name = "city", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "agent", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "street", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "region", namespace = "http://schemas.google.com/g/2005", type = JAXBElement.class, required = false)
    })
    protected List<Object> agentOrCityOrCountry;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "mailClass")
    protected String mailClass;
    @XmlAttribute(name = "primary")
    protected Boolean primary;
    @XmlAttribute(name = "rel")
    protected String rel;
    @XmlAttribute(name = "usage")
    protected String usage;

    /**
     * Gets the value of the agentOrCityOrCountry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentOrCityOrCountry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentOrCityOrCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Country }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getAgentOrCityOrCountry() {
        if (agentOrCityOrCountry == null) {
            agentOrCityOrCountry = new ArrayList<Object>();
        }
        return this.agentOrCityOrCountry;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the mailClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailClass() {
        return mailClass;
    }

    /**
     * Sets the value of the mailClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailClass(String value) {
        this.mailClass = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimary(Boolean value) {
        this.primary = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel(String value) {
        this.rel = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsage(String value) {
        this.usage = value;
    }

}
