//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package com.google.schemas.contact._2008;

import org.simpleframework.xml.Attribute;


/**
 * Birthday date, given in format YYYY-MM-DD (with the year), or --MM-DD (without the year).
 */
public class Birthday {

    @Attribute(name = "when")
    protected String when;

    public String getWhen() {
        return when;
    }

    public void setWhen(String value) {
        this.when = value;
    }

}
