//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.20 at 03:03:46 PM CST 
//


package org.w3._2007.app;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.google.schemas.g._2005.AppDraft;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2007.app package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Edited_QNAME = new QName("http://www.w3.org/2007/app", "edited");
    private final static QName _Control_QNAME = new QName("http://www.w3.org/2007/app", "control");
    private final static QName _Draft_QNAME = new QName("http://www.w3.org/2007/app", "draft");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2007.app
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2007/app", name = "edited")
    public JAXBElement<String> createEdited(String value) {
        return new JAXBElement<String>(_Edited_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AppDraft }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2007/app", name = "control")
    public JAXBElement<AppDraft> createControl(AppDraft value) {
        return new JAXBElement<AppDraft>(_Control_QNAME, AppDraft.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2007/app", name = "draft")
    public JAXBElement<String> createDraft(String value) {
        return new JAXBElement<String>(_Draft_QNAME, String.class, null, value);
    }

}
